config/routes.rb
Rails.application.routes.draw do

  root'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'forum' => 'topics#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topics do 
    resources :comments do
      member do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :votes, dependent: :destroy
  #validates :author, presence: true, length: {minimum: 3}
  validates :text, presence: true, length: {minimum: 10}
  validates :user_id, presence: true
  validates :topic_id, presence: true
  default_scope -> {order(created_at: :desc)}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  
  def create
    @topic = Topic.find(params[:topic_id])
    @comments = @topic.comments

    @comment = current_user.comments.build(comment_params)
    @comment.topic = @topic

    if @comment.save
      flash[:notice] = "Comment was created."
      redirect_to topic_path(@topic)
    else
      flash[:error] = "There was an error saving the comment. Please try again."
      redirect_to topic_path(@topic)
    end

    #@comment = @topic.comments.create(comment_params)
    #redirect_to topic_path(@topic)
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    @comment.destroy
    redirect_to topic_path(@topic) 
  end

  def upvote
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    @comment.votes.create
    redirect_to topic_path(@topic)
  end

  def downvote
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.find(params[:id])
    @comment.votes.last.destroy
    redirect_to topic_path(@topic)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:text, :topic_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<table style="table-layout: fixed; width: 75%">
  <tr>
    <td style="width: 10%"> <%= button_to 'UpVote', upvote_topic_comment_path(comment.topic, comment), method: :post%> 
    </td>
    <td>
      <li class="comments">
        <span><%= link_to gravatar_for(comment.user, size: 50), comment.user %></span>

        <span class="user"><%= link_to comment.user.name, comment.user %></span>
        <span class="content"><%= comment.text %>
        <span class="timestamp">
        Posted <%= time_ago_in_words(comment.created_at) %> ago.
        <% if current_user?(comment.topic.user) %>
        <%= link_to "delete", [comment.topic, comment], method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
       </span>
     </li>
   </td> 
  </tr>
  <tr>
    <td> <%= pluralize(comment.votes.count, "vote") %> </td>
  </tr>
  <tr>
    <td> <%= button_to 'DownVote', downvote_topic_comment_path(comment.topic, comment), method: :post%> </td>  
  </tr>
 </table>

app/views/comments/_form.html.erb
<%= form_for([@topic, @topic.comments.build]) do |t| %> 
  
  <p>
    <%= t.label :text %><br>
    <%= t.text_area :text %>
  </p>

  <p>
    <%= t.submit%>
  </p>
<% end %>