config/routes.rb
Rails.application.routes.draw do

  root'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'forum' => 'topics#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topics do 
    resources :comments do
      member do
        post 'upvote'
        post 'downvote'
      end
    end
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5}
  #validates :author, presence: true, length: {minimum: 3}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  default_scope -> {order(created_at: :desc)} 
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  #has_many :comments
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  
  def new
    @topic = Topic.new
  end

  def create
    #render plain: params[:topic].inspect
    #@topic = Topic.new(topic_params)
    @topic = current_user.topics.build(topic_params)
    if @topic.save
      #redirect_to @topic
      flash[:success] = "Dicscussion topics created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    if @topic.update(topic_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def index
    @topics = Topic.all
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :content)
  end

  def correct_user
    @topic = current_user.topics.find_by(id: params[:id])
    redirect_to root_url if @topic.nil?
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |t| %>
  <% if @topic.errors.any? %>
    <div id ="error_explanation">
      <h2>
        <%=pluralize(@topic.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= t.label :title %><br>
    <%= t.text_field :title %>
  </p>

   <p>
    <%= t.label :content %><br>
    <%= t.text_area :content %>
  </p>

  <p>
    <%= t.submit%>
  </p>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>
<%= render 'form' %>
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing Topics</h1>
<%= link_to 'New Topic', new_topic_path %>
<table>
  <tr>
    <th> Title </th>
    <th> Author </th>
   <!-- <th> Content </th> -->
    <th colspan = "3"></th>
  </tr>

  <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.title %></td>
      <td><%= link_to topic.user.name, topic.user %></td>
      <!-- <td><%= topic.content %></td> -->
      <td><%= link_to 'show', topic_path(topic) %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Delete', topic_path(topic), method: :delete, data:{ confirm: 'Are you sure you want to delete this topic?' } %></td>
    </tr>
  <%end%> 
</table>

app/views/topics/new.html.erb
<h1>New Discussion Topic</h1>
<%= render 'form' %>
<%= link_to 'Back', topics_path %>

app/views/topics/old_form.html.erb
<%= form_for @topic do |t| %>
  <% if @topic.errors.any? %>
    <div id ="error_explanation">
      <h2>
        <%=pluralize(@topic.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= t.label :title %><br>
    <%= t.text_field :title %>
  </p>

  <p>
    <%= t.label :author %><br>
    <%= t.text_field :author %>
  </p> 

  <p>
    <%= t.label :content %><br>
    <%= t.text_area :content %>
  </p>

  <p>
    <%= t.submit%>
  </p>
<% end %>

app/views/topics/oldedit.html.erb
<h1>Editing Topic</h1>
<%= render 'form' %>
<%= link_to 'Back', topics_path %>

app/views/topics/oldindex.html.erb
<h1>Listing Topics</h1>
<%= link_to 'New Topic', new_topic_path %>
<table>
  <tr>
    <th> Title </th>
    <th> Author </th>
   <!-- <th> Content </th> -->
    <th colspan = "3"></th>
  </tr>

  <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.title %></td>
      <td><%= topic.author %></td>
      <!-- <td><%= topic.content %></td> -->
      <td><%= link_to 'show', topic_path(topic) %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Delete', topic_path(topic), method: :delete, data:{ confirm: 'Are you sure you want to delete this topic?' } %></td>
    </tr>
  <%end%> 
</table>

app/views/topics/oldnew.html.erb
<h1>New Discussion Topic</h1>
<%= render 'form' %>
<%= link_to 'Back', topics_path %>

app/views/topics/oldshow.html.erb
<p>
  <strong> Title: </strong>
  <%= @topic.title %>
</p>

<p>
  <strong> Author: </strong>
  <%= @topic.author %>
</p>

<p>
  <strong> Content: </strong>
  <%= @topic.content %>
</p>

<h2>Comments</h2>
<%= render @topic.comments %>

<h2>Add a comment</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', topics_path %> 
<%= link_to 'Edit', edit_topic_path(@topic)%>

app/views/topics/show.html.erb
<li class="topics">
  <%= link_to gravatar_for(@topic.user, size: 50), @topic.user %>
  
  <span><%= @topic.title %></span>
  <span class="user"><%= link_to @topic.user.name, @topic.user %></span>
  <span class="content"><%= @topic.content %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(@topic.created_at) %> ago.
    <% if current_user?(@topic.user) %>
      <%= link_to "delete", @topic, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %> 
  </span>

  <%= render @topic.comments %> 
  
</li>

<h2>Add a comment</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', topics_path %> 
<%= link_to 'Edit', edit_topic_path(@topic)%>